### ISSUE TITLE
Criar uma Programação dos workshops

### ISSUE THREAD

**Issue by SteffanoP** [ifpe-open-source/workshops#1]
A ideia é se reunir em grupo com quem quer fazer workshops e também ouvir da comunidade o que a comunidade quer entender

**Comment by fabiopapais** [comment]
Opa Steffano! Tudo bem?

Já faz um tempo que divulgamos um formulário pelo Whatsapp e Instagram para mapear os interesses da comunidade. Esses são os resultados de uma das perguntas contidas no questionário: 
![image](https://user-images.githubusercontent.com/56613389/115720274-4cbd0080-a353-11eb-9163-afe6d951af88.png)
Baseados nesses interesses predominantes, estamos preparando alguns workshops iniciais, como o de [Criação de Sites](https://github.com/ifpe-open-source/workshops/tree/main/Cria%C3%A7%C3%A3o%20de%20sites), Arduino, entre outros. Aos poucos vamos formalizando o formato dos workshops e queremos com certeza que a própria comunidade proponha coisas novas! Falamos um pouco sobre isso na [apresentação do IFPE Open Source feita antes do workshop de Criação de Sites](https://youtu.be/Ykh5OCnS0HI).

**Comment by weltonfelix** [comment]
Fábio já explicou bem a ideia, então vou fechar esta issue. Qualquer ideia de workshop ou interesse em participar, pode falar com a gente pelo grupo no WhatsApp ou por e-mail (contato@ifpeopensource.com.br).

**Comment by SteffanoP** [comment]
Eu me referia mesmo em montar um calendário com workshops...
